### ISSUE TITLE
Cannot install package using pip: cannot find CHANGELOG.rst

### ISSUE THREAD

**Issue by goindwalia** [fulfilio/python-flipkart#1]
pip install python-flipkart
Downloading/unpacking python-flipkart
  Downloading python-flipkart-0.2.0.tar.gz
  Running setup.py (path:/tmp/pip-build-R7gnLL/python-flipkart/setup.py) egg_info for package python-flipkart
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-R7gnLL/python-flipkart/setup.py", line 30, in <module>
        with open('CHANGELOG.rst') as history_file:
    IOError: [Errno 2] No such file or directory: 'CHANGELOG.rst'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-R7gnLL/python-flipkart/setup.py", line 30, in <module>

    with open('CHANGELOG.rst') as history_file:

IOError: [Errno 2] No such file or directory: 'CHANGELOG.rst'

**Comment by goindwalia** [comment]
Seems CHANGELOG.rst just is not included into package.
