### ISSUE TITLE
ImportError: cannot import name 'urlencode'

### ISSUE THREAD

**Issue by jahangir260** [fulfilio/python-flipkart#3]
Today I installed python_flipkart using python3 interpreter, after successful installation when I tried to run program using flipkart library I got the following issue.

>>> from flipkart import FlipkartAPI, Authentication
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/python-flipkart/flipkart/__init__.py", line 7, in <module>
    from .api import FlipkartAPI         # noqa
  File "/python-flipkart/flipkart/api.py", line 4, in <module>
    from urllib import urlencode
ImportError: cannot import name 'urlencode'

It seems that the library still follows python 2.7 syntax
**Solution :**
kindly use from **urllib.parse import urlencode**    in the file 
https://github.com/fulfilio/python-flipkart/blob/7df817a384678a7623253328dc16fd793300dae5/flipkart/api.py#L4

**Comment by pawneshtapish** [comment]
this works for me from urllib.parse import urlencode

**Comment by ahkhalwai** [comment]
rom flipkart import FlipkartAPI, Authentication
Traceback (most recent call last):
File "", line 1, in
File "/python-flipkart/flipkart/init.py", line 7, in
from .api import FlipkartAPI # noqa
File "/python-flipkart/flipkart/api.py", line 4, in
from urllib import urlencode
ImportError: cannot import name 'urlencode'

i just updated 

#4 

urllib.parse import urlencode

**Comment by pawneshtapish** [comment]
try this from urllib.parse import urlencode
